server.port=8045

spring.datasource.url =jdbc:mysql://localhost:1023/rental_db?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.lk.zerocode.tuition_ms_api.controller=TRACE
logging.level.lk.zerocode.tuition_ms_api.service=DEBUG